### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by SquidDev**
- Revert changes to the bit library: it has now been fixed
- Allow using CCTweaks' [`bitop`](https://github.com/SquidDev-CC/CCTweaks-Lua/wiki/bitop-library) library: slight performance gains
- Correctly close file handles after opening them
- Tons of whitespace edits because my editor is stupid: I'm happy to redo this if you like.

### CODE REVIEW

**Comment by ElvishJerricco** [comment]
Seems good to me! Has this been tested at all?

**Comment by SquidDev** [comment]
I've run JVML-JIT using this and it seems to work correctly (both with and without CCTweaks).

**Comment by ElvishJerricco** [comment]
Cool. That'd be a good pull request for JVML-JIT while you're at it.

**Comment by SquidDev** [comment]
Yeah, I'm working on a couple of things for JVML-JIT. I want to fix SquidDev/luaj.luajc#14 before anything else though.

**Comment by ElvishJerricco** [comment]
Thanks!

**Pull request merged**
